# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode
pool:
  vmImage: 'macOS-10.14'
  # vmImage: 'macOS-latest'

variables:
  projectName: 'Yelp Demo'
  scheme: 'Yelp Demo'
  sdk: 'iphoneos'
  configuration: 'Release'

steps:

- task: CocoaPods@0
  inputs:
    forceRepoUpdate: false
  displayName: 'pod install using the CocoaPods task with a forced repo update and a custom project directory'

# - script: /usr/local/bin/pod install
#   displayName: 'pod install using a script'

# The `certSecureFile` and `provProfileSecureFile` files are uploaded to the Azure Pipelines secure files library where they are encrypted.
# The `P12Password` variable is set in the Azure Pipelines pipeline editor and marked 'secret' to be encrypted.
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'RBC-Dominion-Securities-Inc-Distribution-Signing-Cert.p12'
    certPwd: $(P12Password)

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'Yelp_Demo_Poc.mobileprovision'
    # provProfileSecureFile: 'Yelp_Demo_Poc_Development_Profile.mobileprovision'
    removeProfile: true
    
- task: Xcode@5
  inputs:
    actions: 'archive'
    sdk: '$(sdk)'
    scheme: 'Yelp Demo'
    configuration: '$(configuration)'
    xcodeVersion: 'default'
    # Options: default, 10, 9, 8, specifyPath
    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
    exportOptions: 'plist' # Optional. Options: auto, plist, specify
    #exportMethod: 'development' # Required when exportOptions == Specify
    #exportTeamId: # Optional
    exportOptionsPlist: 'exportOptions.plist' # Required when exportOptions == Plist
    #exportArgs: # Optional
    archivePath: '$(agent.buildDirectory)/output/archive/'
    packageApp: true
    # xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    # xcWorkspacePath: '**/$(projectName).xcworkspace'
    xcWorkspacePath: '**/Yelp\ Demo.xcworkspace'
    useXcpretty: false
    signingOption: 'default'
    # args: 'PROVISIONING_PROFILE=edaa3024-18ee-4a97-ba57-772ce08b5677'
    # provisioningProfileName: 'Yelp Demo Poc'
    # Development Provisioning Profile UUID
    # provisioningProfileUuid: '1e5c3bb1-37c9-41a6-a4cb-fb3b14f54fb1'
    # Distribution Provisioning Profile UUID
    # provisioningProfileUuid: 'edaa3024-18ee-4a97-ba57-772ce08b5677'
    # teamId: '8KLLEZRH9Y'

# - task: Xcode@5
#   inputs:
#     actions: 'build'
#     scheme: ''
#     sdk: 'iphoneos'
#     configuration: 'Release'
#     xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
#     xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
#     signingOption: 'default' # Options: nosign, default, manual, auto
#     useXcpretty: 'false' # Makes it easier to diagnose build failures

- task: CopyFiles@2
  inputs:
    contents: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)/*.ipa'
    targetFolder: '$(build.artifactStagingDirectory)'

# - task: PublishBuildArtifacts@1
#   inputs:
#     pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
#     artifactName: 'drop' 
#     publishLocation: 'filePath' # Options: container, filePath
#     targetPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)/'# Required when publishLocation == FilePath
#     #parallel: false # Optional
#     #parallelCount: # Optional

# App Center distribute
# Distribute app builds to testers and users via Visual Studio App Center
- task: AppCenterDistribute@3
  inputs:
    serverEndpoint: 'App Center'
    appSlug: 'ken_mau/Yelp-Demo-Poc'
    appFile: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)/*.ipa'
    #symbolsOption: 'Apple' # Optional. Options: apple, android
    #symbolsPath: # Optional
    #symbolsPdbFiles: '**/*.pdb' # Optional
    #symbolsDsymFiles: # Optional
    #symbolsMappingTxtFile: # Optional
    #symbolsIncludeParentDirectory: # Optional
    releaseNotesOption: 'input' # Options: input, file
    #releaseNotesFile: # Required when releaseNotesOption == File
    releaseNotesInput: 'Test'# Required when releaseNotesOption == Input
    #isMandatory: false # Optional
    #destinationType: 'groups' # Options: groups, store
    #distributionGroupId: # Optional
    #destinationStoreId: # Required when destinationType == Store
    #isSilent: # Optional